### ISSUE TITLE
batch_extract_all_scenes_and_fuse

### ISSUE THREAD

**Issue by peteflorence** [RobotLocomotion/spartan#285]
Failed with file not found error on iiwa1 machine.

```
output_dir:  /home/peteflo/spartan/data_volume/pdc/logs_proto/2018-04-24-16-09-58/processed
cmd:
cd /home/peteflo/spartan/src/tsdf-fusion && /home/peteflo/spartan/src/tsdf-fusion/demo /home/peteflo/spartan/data_volume/pdc/logs_proto/2018-04-24-16-09-58/processed/images /home/peteflo/spartan/data_volume/pdc/logs_proto/2018-04-24-16-09-58/processed/images/camera-intrinsics.txt 0.0025 240 320 280 0.4 -0.3 -0.2
Traceback (most recent call last):
  File "./batch_extract_and_fuse_all_scenes.py", line 64, in <module>
    tsdf_fusion.run_tsdf_fusion_cuda(images_dir)
  File "/home/peteflo/spartan/build/install/lib/python2.7/dist-packages/fusion_server/tsdf_fusion.py", line 113, in run_tsdf_fusion_cuda
    shutil.move(tsdf_bin, tsdf_bin_new)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/peteflo/spartan/data_volume/pdc/logs_proto/2018-04-24-16-09-58/processed/images/tsdf.bin'

```

**Comment by manuelli** [comment]
I think this is working fine now.
