### ISSUE TITLE
no such package '@snopt//'

### ISSUE THREAD

**Issue by kingsman142** [RobotLocomotion/spartan#377]
I'm currently following this guide: https://github.com/RobotLocomotion/spartan/blob/master/setup/docker/README.md and I made it to the last line where I have to `make -j` spartan. I've also set up the ssh keys correctly I believe, or I would not have made it to this step. Despite this, I receive the following two errors and my build fails:

[ 29%] Built target pybind11
-- Found Bazel: /usr/bin/bazel (found suitable version "0.21.0", minimum required is "0.19.2") 
-- Found PythonInterp: /usr/bin/python2 (found suitable exact version "2.7.12") 
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/james/spartan/build/drake
[ 30%] Performing build step for 'drake'
Scanning dependencies of target drake_cxx_python
[ 12%] Creating directories for 'drake_cxx_python'
[ 25%] No download step for 'drake_cxx_python'
[ 50%] No update step for 'drake_cxx_python'
[ 50%] No patch step for 'drake_cxx_python'
[ 62%] Performing configure step for 'drake_cxx_python'
[ 75%] Performing build step for 'drake_cxx_python'
Starting local Bazel server and connecting to it...
INFO: Invocation ID: c07a8816-7d2e-4ae1-9056-1d138224d533
ERROR: /home/james/spartan/drake/solvers/BUILD.bazel:735:1: no such package '@snopt//': Traceback (most recent call last):
	File "/home/james/spartan/build/drake/_bazel_/6a242f2d6d1177c198b7f921704eb9bb/external/drake/tools/workspace/snopt/repository.bzl", line 150
		_setup_git(repo_ctx)
	File "/home/james/spartan/build/drake/_bazel_/6a242f2d6d1177c198b7f921704eb9bb/external/drake/tools/workspace/snopt/repository.bzl", line 60, in _setup_git
		_git_clone(repo_ctx, remote = repo_ctx.attr.r..., ...)
	File "/home/james/spartan/build/drake/_bazel_/6a242f2d6d1177c198b7f921704eb9bb/external/drake/tools/workspace/snopt/repository.bzl", line 47, in _git_clone
		_run_git(repo_ctx, "clone", remote, ".")
	File "/home/james/spartan/build/drake/_bazel_/6a242f2d6d1177c198b7f921704eb9bb/external/drake/tools/workspace/snopt/repository.bzl", line 27, in _run_git
		_execute(repo_ctx, "git", (["git", "--git-dir...)))
	File "/home/james/spartan/build/drake/_bazel_/6a242f2d6d1177c198b7f921704eb9bb/external/drake/tools/workspace/snopt/repository.bzl", line 16, in _execute
		fail("Repository rule @{} error {} du...))))
Repository rule @snopt error 128 during git operation: "Cloning into '.'...\nERROR: Repository not found.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n" and referenced by '//solvers:snopt_solver'
ERROR: Analysis of target '//:install' failed; build aborted: no such package '@snopt//': Traceback (most recent call last):
	File "/home/james/spartan/build/drake/_bazel_/6a242f2d6d1177c198b7f921704eb9bb/external/drake/tools/workspace/snopt/repository.bzl", line 150
		_setup_git(repo_ctx)
	File "/home/james/spartan/build/drake/_bazel_/6a242f2d6d1177c198b7f921704eb9bb/external/drake/tools/workspace/snopt/repository.bzl", line 60, in _setup_git
		_git_clone(repo_ctx, remote = repo_ctx.attr.r..., ...)
	File "/home/james/spartan/build/drake/_bazel_/6a242f2d6d1177c198b7f921704eb9bb/external/drake/tools/workspace/snopt/repository.bzl", line 47, in _git_clone
		_run_git(repo_ctx, "clone", remote, ".")
	File "/home/james/spartan/build/drake/_bazel_/6a242f2d6d1177c198b7f921704eb9bb/external/drake/tools/workspace/snopt/repository.bzl", line 27, in _run_git
		_execute(repo_ctx, "git", (["git", "--git-dir...)))
	File "/home/james/spartan/build/drake/_bazel_/6a242f2d6d1177c198b7f921704eb9bb/external/drake/tools/workspace/snopt/repository.bzl", line 16, in _execute
		fail("Repository rule @{} error {} du...))))
Repository rule @snopt error 128 during git operation: "Cloning into '.'...\nERROR: Repository not found.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
INFO: Elapsed time: 6.643s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (183 packages loaded, 3482 targets configured)
    currently loading: @eigen//
    Fetching @json; fetching
    Fetching @snopt; fetching
    Fetching @bullet; fetching
    Fetching @vtk; fetching
    Fetching @meshcat; fetching
    Fetching @optitrack_driver; fetching
    Fetching @fcl; fetching
    Fetching @u_msgpack_python; fetching ... (14 fetches)
CMakeFiles/drake_cxx_python.dir/build.make:110: recipe for target 'drake_cxx_python-prefix/src/drake_cxx_python-stamp/drake_cxx_python-build' failed
make[5]: *** [drake_cxx_python-prefix/src/drake_cxx_python-stamp/drake_cxx_python-build] Error 1
CMakeFiles/Makefile2:387: recipe for target 'CMakeFiles/drake_cxx_python.dir/all' failed
make[4]: *** [CMakeFiles/drake_cxx_python.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/drake.dir/build.make:111: recipe for target 'src/drake-stamp/drake-build' failed
make[2]: *** [src/drake-stamp/drake-build] Error 2
CMakeFiles/Makefile2:179: recipe for target 'CMakeFiles/drake.dir/all' failed
make[1]: *** [CMakeFiles/drake.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by manuelli** [comment]
@kingsman142 Unfortunately `spartan` is really a tool meant for internal lab use (as stated in the main README), not for use by the broader community. I think your issue arises from insufficient permissions

**Comment by Amulya21** [comment]
Hii,
Even i am facing the same issue.what to do? How to resolve this issue?
